import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const bahnschrift = localFont({ src: "../../public/fonts/Bahnschrift-Font-Family/Bahnschrift.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bahnschrift.className} ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
